language: erlang

# Choose which platforms you want your builds run against (done in parallel)
env:
   - ST=PharoCore-1.0  # pharo 1.0 needs a different VM
   - ST=PharoCore-1.1
   - ST=PharoCore-1.2
   - ST=PharoCore-1.3
   - ST=Pharo-1.4
   - ST=Pharo-2.0 # Pharo-2.0 until Issue #12 fixed
   - ST=Squeak-4.3
   - ST=Squeak-4.4
   - ST=Squeak-4.5 # until https://github.com/dalehenrich/metacello-work/issues/155 fixed
   - ST=GemStone-2.4.4.1
   - ST=GemStone-2.4.4.7
   - ST=GemStone-2.4.5
   - ST=GemStone-2.4.5.1
   - ST=GemStone-3.0.1
   - ST=GemStone-3.1.0.2

# Boilerplate ... should be no reason to edit the install section
install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/SWTI2014/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd SWTI2014-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

# use a different script if you want to customize how travis tests are run
# use verbose flag to dump transcript unconditionally
script: $BUILDER_CI_HOME/testTravisCI.sh # -verbose 